---
title: "Correspondence analysis"
author: "liuc"
date: "11/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Correspondence analysis

对应分析,以及去势对应分析用于分类

```{r}
library(medicaldata)
library(tidymodels)
library(MASS)
library(discrim)
```


## Discriminant Analysis is more stable than logistic regression for multi-class 

http://www.sthda.com/english/articles/36-classification-methods-essentials/146-discriminant-analysis-essentials-in-r/

判别分析包括有多个变种，包括线性判别分析、mixture DA, Flexible DA....
下面为lda线性判别分析的一般过程

```{r}
# preprocess the data
df_split <- initial_split(iris, prop = 0.8)
X_train <- training(df_split)
X_test <- testing(df_split)
# lda 可以考虑对输入矩阵进行标准化scale


# build model
discrim_linear_MASS_spec <-
  discrim_linear() %>%
  set_engine('MASS')

discrim_fit <- discrim_linear_MASS_spec %>% 
  fit(Species ~ ., data = X_train)

fit_res <- X_test %>% 
  dplyr::select(Species) %>% 
  bind_cols(predict(discrim_fit, X_test))

predict(discrim_fit$fit)
```

metrics, 以及提取模型本身的参数

```{r}
conf_mat(fit_res, truth = Species, estimate = .pred_class)
```


### use MASS for lda analysis
tidymodels 似乎还没有特别成熟

```{r}
model <- lda(
  Species ~ ., data = X_train
)

model # 和discrim_fit$fit不一致就很烦人了

ggplot(cbind(X_train, predict(model)$x), aes(LD1, LD2, color = Species)) +
  geom_point() +
  stat_ellipse(level = 0.95, show.legend = FALSE) + theme_bw()

```

### 二次判别分析

二次判别分析由于不假定个类别的协方差相等，因此比lda较为灵活一些，对于样本量较大的数据可以采用qda

```{r}
pda_moodel <- qda(
  Species ~ ., data = X_train
)

```


### 混合判别分析

```{r}
library(mda)
```



