---
title: "feature selection"
format: html
---

# feature selection in R

> https://jtr13.github.io/cc21fall2/feature-selection-in-r.html
> https://cran.r-project.org/web/packages/familiar/vignettes/feature_selection_precompiled.html
> http://r-statistics.co/Variable-Selection-and-Importance-With-R.html


There are several popular feature selection methods in machine learning. Here are some of the most commonly used ones:

Recursive Feature Elimination (RFE): This method recursively removes features from the dataset and evaluates the performance of the model at each step. It selects the subset of features that results in the best model performance.

Principal Component Analysis (PCA): PCA is a technique that transforms the original features into a new set of uncorrelated features (principal components) that explain the maximum amount of variance in the data. The principal components can be used as features for the model.

Lasso regularization: Lasso is a regularization technique that adds a penalty term to the objective function of the model. The penalty term encourages the model to select a sparse set of features by shrinking the coefficients of less important features to zero.

Mutual Information: This method measures the mutual information between each feature and the target variable. It selects the subset of features with the highest mutual information.

Tree-based feature selection: This method uses decision trees to evaluate the importance of each feature. It selects the subset of features with the highest importance scores.

Correlation-based feature selection: This method evaluates the correlation between each feature and the target variable. It selects the subset of features with the highest correlation.



# Feature Selection packages in R

Feature selection or variable selection in machine learning is the process of selecting a subset of relevant features (variables or predictors) for use in model construction.

Introduction to feature selection: https://www.analyticsvidhya.com/blog/2016/12/introduction-to-feature-selection-methods-with-an-example-or-how-to-select-the-right-variables/

## Packages

### FSinR

Examples: <br>
https://cran.r-project.org/web/packages/FSinR/vignettes/FSinR.html <br>
CRAN pdf: <br>
https://cran.r-project.org/web/packages/FSinR/FSinR.pdf

### Boruta

Examples: <br>
https://www.analyticsvidhya.com/blog/2016/03/select-important-variables-boruta-package/ <br>
https://www.datacamp.com/community/tutorials/feature-selection-R-boruta <br>
https://www.listendata.com/2017/05/feature-selection-boruta-package.html <br>
http://www.cybaea.net/Journal/2010/11/15/Feature-selection-All-relevant-selection-with-the-Boruta-package/ <br>
CRAN pdf: <br>
https://cran.r-project.org/web/packages/Boruta/Boruta.pdf

### caret

Examples: <br>
http://ml-tutorials.kyrcha.info/rfe.html <br>
http://www.cybaea.net/Journal/2010/11/16/Feature-selection-Using-the-caret-package/ <br>
https://machinelearningmastery.com/feature-selection-with-the-caret-r-package/ <br>
CRAN pdf: <br>
https://cran.r-project.org/web/packages/caret/caret.pdf

### spFSR

Examples: <br>
https://cran.r-project.org/web/packages/spFSR/vignettes/spFSR.html <br>
CRAN pdf: <br>
https://cran.r-project.org/web/packages/spFSR/spFSR.pdf

### varSelRF

Examples: <br>
https://www.kaggle.com/netzone/mushroom-classification-using-varselrf <br>
CRAN pdf: <br>
https://cran.r-project.org/web/packages/varSelRF/varSelRF.pdf

### CORElearn

Examples: <br>
https://ucilnica.fri.uni-lj.si/pluginfile.php/24621/mod_resource/content/3/lab%205%20-%20attribute%20evaluation.R <br>
CRAN pdf: <br>
https://cran.r-project.org/web/packages/CORElearn/CORElearn.pdf

### FSelector

Examples: <br>
https://miningthedetails.com/blog/r/fselector/  <br>
CRAN pdf: <br>
https://cran.r-project.org/web/packages/FSelector/FSelector.pdf

### EFS

Examples: <br>
https://biodatamining.biomedcentral.com/articles/10.1186/s13040-017-0142-8  <br>
CRAN pdf: <br>
https://cran.r-project.org/web/packages/EFS/EFS.pdf

### RWeka

CRAN pdf: <br>
https://cran.r-project.org/web/packages/RWeka/RWeka.pdf

### featurefinder

CRAN pdf: <br>
https://cran.r-project.org/web/packages/featurefinder/featurefinder.pdf

### more...

mRMRe: A package that implements the minimum redundancy maximum relevance algorithm, a feature selection method that selects features that are both relevant to the target variable and not redundant with each other.

Rborist: A package that implements the Borist algorithm, a feature selection method that evaluates the importance of features by comparing them with a random forest model.

CORElearn: A package that includes several feature selection methods, such as ReliefF and Correlation-based Feature Selection.

caretEnsemble: A package that includes several ensemble feature selection methods, such as recursive feature elimination and forward selection.




























