---
title: "linear mixed effect model"
author: "liuc"
date: "10/28/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## linear mixed effect model

```{r}
library(tidyverse)
library(easystats)
library(lme4)
library(lmerTest)


# data(package = 'lme4')
```

## use lmer

```{r}
# df2 data as in gee.Rmd
lme_model <- 
  lme4::lmer(score ~ time * class + AGE + (1|`PatientID`),
             data = df2
             )
summary(lme_model)
```

**结果解读：**lme模型和gee.Rmd中的示例为同一数据，我们在只考虑随机截距的情况下，Fixed effects中Estimate值和gee结果保持一致，说明自变量。random effects为随机效应， Group列为随机效应因素

```{r}
# to see all 134 models
coef(lme_model)

library(ggeffects)

plot(ggemmeans(lme_model, terms = c("time", "class"), 
               condition = c(diagnose = "severe"))) + 
  ggplot2::ggtitle("GLMER Effect plot")
```

```{r}

ggpredict(
  model = lme_model,
  terms = c('time', 'class')
)

(lme_pre <- ggpredict(
  model = lme_model,
  terms = c('time', 'class'),
  type = 'random'
))
```

use easystats to get model parameter or effectsize or performance

```{r}
performance::performance(lme_model)

# insight::get_variance(lme_model) # show all variance

parameters::parameters(lme_model)
```

use glmer

```{r}
glme_model <- 
  lme4::glmer(
    score ~ time * class + AGE + (1|`PatientID`),
             data = df2,
             family = 'gaussian'
  )

summary(glme_model)
```

```{r}

compare_performance(lme_model, glme_model)

plot(compare_performance(lme_model, glme_model))
```
